[action] [PR:19071] voqWD disabling and method to check dshellClient is running (#435)
### Description of PR
Disabling voqWD in testcase where PFCWD is disabled and traffic is run for more than 1min. Added a method to check if dshell client is up and running

Summary:
Fixes #
`FAILED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info0-port_map0] - Failed: Losses observed in lossy traffic streams`

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
 - [ ] Skipped for non-supported platforms
- [X ] Test case improvement

### Back port request
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [X ] 202405
- [ ] 202411
- [ ] 202505

### Approach
#### What is the motivation for this PR?
We had added the fixture to disable the voqWD.
https://github.com/sonic-net/sonic-mgmt/blob/939485fd3e5d890de5d94f3b7eedd44e82844180/tests/snappi_tests/pfcwd/test_pfcwd_actions.py#L18

But every tests does config reload on the DUT’s which reverses disabled voqWD config.
Hence the test was failing
 FAILED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info0-port_map0] - Failed: Losses observed in lossy traffic streamsWe had added the fixture to disable the voqWD.

config reload done as part of teardown:
https://github.com/sonic-net/sonic-mgmt/blob/939485fd3e5d890de5d94f3b7eedd44e82844180/tests/snappi_tests/pfcwd/test_pfcwd_actions.py#L885

#### How did you do it?
Disabling the voqWD in the test case where PFCWD is disabled and traffic is sent for > 1min

#### How did you verify/test it?
Manually ran the tests with change

```
========================= short test summary info =========================================
PASSED snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py::test_multidut_pfcwd_all_to_all[multidut_port_info0-True]
PASSED snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py::test_multidut_pfcwd_all_to_all[multidut_port_info0-False]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_90_10[multidut_port_info0-port_map0]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_uni[multidut_port_info0-port_map0]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_over_subs_40_09[multidut_port_info0-port_map0]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info0-port_map0]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_single_lossless_prio[multidut_port_info0-True]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_single_lossless_prio[multidut_port_info0-False]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_multi_lossless_prio[multidut_port_info0-True]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_multi_lossless_prio[multidut_port_info0-False]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_single_lossless_prio_reboot[multidut_port_info0-cold-yy40-mixed-rp|4-True]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_multi_lossless_prio_reboot[multidut_port_info0-cold-True]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_multi_lossless_prio_reboot[multidut_port_info0-cold-False]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_single_lossless_prio_service_restart[multidut_port_info0-True-swss]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_single_lossless_prio_service_restart[multidut_port_info0-False-swss]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_multi_lossless_prio_restart_service[multidut_port_info0-True-swss]
PASSED snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py::test_pfcwd_basic_multi_lossless_prio_restart_service[multidut_port_info0-False-swss]
PASSED snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py::test_pfcwd_burst_storm_single_lossless_prio[multidut_port_info0]
PASSED snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py::test_pfcwd_many_to_one[multidut_port_info0-True]
PASSED snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py::test_pfcwd_many_to_one[multidut_port_info0-False]
PASSED snappi_tests/pfcwd/test_pfcwd_mixed_speed.py::test_mixed_speed_pfcwd_enable[multidut_port_info0-port_map0]
PASSED snappi_tests/pfcwd/test_pfcwd_mixed_speed.py::test_mixed_speed_pfcwd_disable[multidut_port_info0-port_map0]
PASSED snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py::test_pfcwd_runtime_traffic[multidut_port_info0]
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_actions.py:370: Forward action is not supported in cisco-8000.
SKIPPED [1] common/helpers/assertions.py:22: Need Minimum of 2 ports defined in ansible/files/*links.csv file
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_actions.py:715: Forward action is not supported in cisco-8000.
SKIPPED [1] snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py:141: Reboot type warm is not supported on cisco-8000 switches
SKIPPED [1] snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py:141: Reboot type fast is not supported on cisco-8000 switches
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py:190: Reboot type warm is not supported on cisco-8000 switches
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py:190: Reboot type fast is not supported on cisco-8000 switches
FAILED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_90_10[multidut_port_info0-port_map1] - Failed: Rx Ports for yy40-mixed-tb in MULTIDUT_PORT_INFO doesn't match with ansible/files/*links.csv
FAILED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_uni[multidut_port_info0-port_map1] - Failed: Rx Ports for yy40-mixed-tb in MULTIDUT_PORT_INFO doesn't match with ansible/files/*links.csv
FAILED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info0-port_map1] - Failed: Rx Ports for yy40-mixed-tb in MULTIDUT_PORT_INFO doesn't match with ansible/files/*links.csv
=========== 3 failed, 23 passed, 11 skipped, 22 warnings in 17703.22s (4:55:03) ===================
```

#### Any platform specific information?
Cisco8000